import { Categoria } from './arbol.interaces';

export const reporte: Categoria[] = [
  {
    id: 15,
    nombre: 'Ingreso',
    tipo: 'in',
    idEmpresa: '11',
    idCategoriaPadre: null,
    orden: '1',
    fechaBorrado: null,
    subcategorias: [
      {
        id: 26,
        nombre: 'Previa',
        tipo: 'in',
        idEmpresa: '11',
        idCategoriaPadre: '15',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [
          {
            id: 878978979,
            nombre: 'Previa',
            tipo: 'in',
            idEmpresa: '11',
            idCategoriaPadre: '26',
            orden: '1',
            fechaBorrado: null,
            subcategorias: [],
            acumulado: {
              total: 3200,
              cajas: [
                {
                  id: 8,
                  nombre: 'Caja Wallas',
                  idUnidadNegocio: '9',
                  negativa: false,
                  fechaBorrado: null,
                  total: 3200,
                },
              ],
            },
          },
        ],
        acumulado: {
          total: 3200,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 3200,
            },
          ],
        },
      },
      {
        id: 27,
        nombre: 'Qr',
        tipo: 'in',
        idEmpresa: '11',
        idCategoriaPadre: '15',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 7800,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 7800,
            },
          ],
        },
      },
      {
        id: 28,
        nombre: 'Qr vencidos',
        tipo: 'in',
        idEmpresa: '11',
        idCategoriaPadre: '15',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 7800,
          cajas: [
            {
              id: 9,
              nombre: 'Caja Wallas VIP',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 7800,
            },
          ],
        },
      },
      {
        id: 29,
        nombre: 'Pleno',
        tipo: 'in',
        idEmpresa: '11',
        idCategoriaPadre: '15',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 95470,
          cajas: [
            {
              id: 9,
              nombre: 'Caja Wallas VIP',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 7800,
            },
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 87670,
            },
          ],
        },
      },
      {
        id: 30,
        nombre: 'Living',
        tipo: 'in',
        idEmpresa: '11',
        idCategoriaPadre: '15',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 0,
          cajas: [],
        },
      },
    ],
    acumulado: {
      total: 114270,
      cajas: [
        {
          id: 8,
          nombre: 'Caja Wallas',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 98670,
        },
        {
          id: 9,
          nombre: 'Caja Wallas VIP',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 15600,
        },
      ],
    },
  },
  {
    id: 16,
    nombre: 'Comida',
    tipo: 'in',
    idEmpresa: '11',
    idCategoriaPadre: null,
    orden: '1',
    fechaBorrado: null,
    subcategorias: [
      {
        id: 31,
        nombre: 'Menu',
        tipo: 'in',
        idEmpresa: '11',
        idCategoriaPadre: '16',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 110000,
          cajas: [
            {
              id: 9,
              nombre: 'Caja Wallas VIP',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 110000,
            },
          ],
        },
      },
      {
        id: 32,
        nombre: 'Carta',
        tipo: 'in',
        idEmpresa: '11',
        idCategoriaPadre: '16',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 110000,
          cajas: [
            {
              id: 9,
              nombre: 'Caja Wallas VIP',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 110000,
            },
          ],
        },
      },
    ],
    acumulado: {
      total: 220000,
      cajas: [
        {
          id: 9,
          nombre: 'Caja Wallas VIP',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 220000,
        },
      ],
    },
  },
  {
    id: 17,
    nombre: 'Bebida',
    tipo: 'in',
    idEmpresa: '11',
    idCategoriaPadre: null,
    orden: '1',
    fechaBorrado: null,
    subcategorias: [
      {
        id: 33,
        nombre: 'Living',
        tipo: 'in',
        idEmpresa: '11',
        idCategoriaPadre: '17',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 456456,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 456456,
            },
          ],
        },
      },
      {
        id: 34,
        nombre: 'General',
        tipo: 'in',
        idEmpresa: '11',
        idCategoriaPadre: '17',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 120000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 120000,
            },
          ],
        },
      },
    ],
    acumulado: {
      total: 576456,
      cajas: [
        {
          id: 8,
          nombre: 'Caja Wallas',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 576456,
        },
      ],
    },
  },
  {
    id: 18,
    nombre: 'Otros',
    tipo: 'in',
    idEmpresa: '11',
    idCategoriaPadre: null,
    orden: '1',
    fechaBorrado: null,
    subcategorias: [
      {
        id: 35,
        nombre: 'Cigarrillos',
        tipo: 'in',
        idEmpresa: '11',
        idCategoriaPadre: '18',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 3000,
          cajas: [
            {
              id: 9,
              nombre: 'Caja Wallas VIP',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 3000,
            },
          ],
        },
      },
      {
        id: 36,
        nombre: 'Guardaropa',
        tipo: 'in',
        idEmpresa: '11',
        idCategoriaPadre: '18',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 1000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 1000,
            },
          ],
        },
      },
    ],
    acumulado: {
      total: 4000,
      cajas: [
        {
          id: 9,
          nombre: 'Caja Wallas VIP',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 3000,
        },
        {
          id: 8,
          nombre: 'Caja Wallas',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 1000,
        },
      ],
    },
  },
  {
    id: 19,
    nombre: 'Operativos Directos',
    tipo: 'out',
    idEmpresa: '11',
    idCategoriaPadre: null,
    orden: '1',
    fechaBorrado: null,
    subcategorias: [
      {
        id: 37,
        nombre: 'Adicional de policia blanco',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '19',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 1000,
          cajas: [
            {
              id: 9,
              nombre: 'Caja Wallas VIP',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 1000,
            },
          ],
        },
      },
      {
        id: 38,
        nombre: 'Adicional de policia negro',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '19',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 9800,
          cajas: [
            {
              id: 9,
              nombre: 'Caja Wallas VIP',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 9800,
            },
          ],
        },
      },
    ],
    acumulado: {
      total: 10800,
      cajas: [
        {
          id: 9,
          nombre: 'Caja Wallas VIP',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 10800,
        },
      ],
    },
  },
  {
    id: 20,
    nombre: 'Sueldos',
    tipo: 'out',
    idEmpresa: '11',
    idCategoriaPadre: null,
    orden: '1',
    fechaBorrado: null,
    subcategorias: [
      {
        id: 39,
        nombre: 'Javier - Encargado General',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '20',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 12000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 12000,
            },
          ],
        },
      },
      {
        id: 40,
        nombre: 'Mario - Encargado deposito',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '20',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 12000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 12000,
            },
          ],
        },
      },
      {
        id: 41,
        nombre: 'Estefania - Encargado cocina',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '20',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 12000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 12000,
            },
          ],
        },
      },
      {
        id: 42,
        nombre: 'Mauro - Encargado noche',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '20',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 12000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 12000,
            },
          ],
        },
      },
    ],
    acumulado: {
      total: 48000,
      cajas: [
        {
          id: 8,
          nombre: 'Caja Wallas',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 48000,
        },
      ],
    },
  },
  {
    id: 21,
    nombre: 'Publicidad y promocion',
    tipo: 'out',
    idEmpresa: '11',
    idCategoriaPadre: null,
    orden: '1',
    fechaBorrado: null,
    subcategorias: [
      {
        id: 43,
        nombre: 'Fotografo',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '21',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 780,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 780,
            },
          ],
        },
      },
      {
        id: 44,
        nombre: 'Diseñador',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '21',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 780,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 780,
            },
          ],
        },
      },
      {
        id: 45,
        nombre: 'Video',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '21',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 12300,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 12300,
            },
          ],
        },
      },
    ],
    acumulado: {
      total: 13860,
      cajas: [
        {
          id: 8,
          nombre: 'Caja Wallas',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 13860,
        },
      ],
    },
  },
  {
    id: 22,
    nombre: 'Artistica + Ambientacion',
    tipo: 'out',
    idEmpresa: '11',
    idCategoriaPadre: null,
    orden: '1',
    fechaBorrado: null,
    subcategorias: [
      {
        id: 46,
        nombre: 'Dj 1',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '22',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 70000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 70000,
            },
          ],
        },
      },
      {
        id: 47,
        nombre: 'Dj 2',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '22',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 70000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 70000,
            },
          ],
        },
      },
    ],
    acumulado: {
      total: 140000,
      cajas: [
        {
          id: 8,
          nombre: 'Caja Wallas',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 140000,
        },
      ],
    },
  },
  {
    id: 23,
    nombre: 'Convocatoria',
    tipo: 'out',
    idEmpresa: '11',
    idCategoriaPadre: null,
    orden: '1',
    fechaBorrado: null,
    subcategorias: [
      {
        id: 48,
        nombre: 'Relaciones Publicas India',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '23',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 6000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 6000,
            },
          ],
        },
      },
      {
        id: 49,
        nombre: 'Relaciones Publicas Wallas',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '23',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 78000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 78000,
            },
          ],
        },
      },
    ],
    acumulado: {
      total: 84000,
      cajas: [
        {
          id: 8,
          nombre: 'Caja Wallas',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 84000,
        },
      ],
    },
  },
  {
    id: 24,
    nombre: 'Comision por venta',
    tipo: 'out',
    idEmpresa: '11',
    idCategoriaPadre: null,
    orden: '1',
    fechaBorrado: null,
    subcategorias: [
      {
        id: 50,
        nombre: 'Early Ticket',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '24',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 1000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 1000,
            },
          ],
        },
      },
      {
        id: 51,
        nombre: 'Mesas Vip',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '24',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 3000,
          cajas: [
            {
              id: 8,
              nombre: 'Caja Wallas',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 3000,
            },
          ],
        },
      },
    ],
    acumulado: {
      total: 4000,
      cajas: [
        {
          id: 8,
          nombre: 'Caja Wallas',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 4000,
        },
      ],
    },
  },
  {
    id: 25,
    nombre: 'Varios',
    tipo: 'out',
    idEmpresa: '11',
    idCategoriaPadre: null,
    orden: '1',
    fechaBorrado: null,
    subcategorias: [
      {
        id: 52,
        nombre: 'Comida personal',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '25',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 7000,
          cajas: [
            {
              id: 9,
              nombre: 'Caja Wallas VIP',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 7000,
            },
          ],
        },
      },
      {
        id: 55,
        nombre: 'TQR',
        tipo: 'out',
        idEmpresa: '11',
        idCategoriaPadre: '25',
        orden: '1',
        fechaBorrado: null,
        subcategorias: [],
        acumulado: {
          total: 7140000,
          cajas: [
            {
              id: 9,
              nombre: 'Caja Wallas VIP',
              idUnidadNegocio: '9',
              negativa: false,
              fechaBorrado: null,
              total: 7140000,
            },
          ],
        },
      },
    ],
    acumulado: {
      total: 7147000,
      cajas: [
        {
          id: 9,
          nombre: 'Caja Wallas VIP',
          idUnidadNegocio: '9',
          negativa: false,
          fechaBorrado: null,
          total: 7147000,
        },
      ],
    },
  },
];
